/**
 * Transfer-record ownership — canonical EIP-5564 view-only detection
 *
 * Regression test for sip-protocol/sip-mobile#85: the background scanner's
 * `checkRecordOwnership` previously derived the stealth scalar from the amount-encryption
 * shared secret via SHA512 + clamp and fed the full 33-byte ephemeral key into the
 * derivation, so it matched NOTHING the send flow / SDK produced (and threw on the 33-byte
 * key → detected nothing). It now routes through the canonical view-only
 * `checkStealthOwnership`, slicing the 33-byte ephemeral prefix, so a payment produced by
 * `generateStealthAddress` is detected with the viewing PRIVATE key + spending PUBLIC key.
 *
 * Lives in its own module (decoupled from src/services/backgroundScan.ts, which loads
 * expo-task-manager / -background-fetch / -notifications at import) so detection is unit
 * testable without native mocks.
 */

import { describe, it, expect } from "vitest"
import { PublicKey } from "@solana/web3.js"
import { ed25519 } from "@noble/curves/ed25519"
import { checkRecordOwnership } from "@/services/recordOwnership"
import {
  generateStealthAddress,
  bytesToHex,
  hexToBytes,
  type StealthAddress,
  type StealthMetaAddress,
} from "@/lib/stealth"
import type { TransferRecordData } from "@/lib/anchor/client"

// Distinct, deterministic recipient seeds (the expo-crypto mock returns a constant buffer,
// so keys are built explicitly to keep spending != viewing).
const SPENDING_SEED = new Uint8Array(32).fill(0x11)
const VIEWING_SEED = new Uint8Array(32).fill(0x22)
const WRONG_VIEWING_SEED = new Uint8Array(32).fill(0x33)

function meta(): StealthMetaAddress {
  return {
    chain: "solana",
    spendingKey: `0x${bytesToHex(ed25519.getPublicKey(SPENDING_SEED))}`,
    viewingKey: `0x${bytesToHex(ed25519.getPublicKey(VIEWING_SEED))}`,
  }
}

// Build a TransferRecordData exactly as the send path stores it (anchor/client.ts): the
// ephemeral key is 33 bytes (0x02 prefix + 32-byte ed25519 R) and the stealth recipient is
// a PublicKey.
function recordFor(stealthAddress: StealthAddress): TransferRecordData {
  const ephemeral33 = new Uint8Array(33)
  ephemeral33[0] = 0x02
  ephemeral33.set(hexToBytes(stealthAddress.ephemeralPublicKey), 1)
  return {
    pubkey: new PublicKey(new Uint8Array(32)),
    sender: new PublicKey(new Uint8Array(32)),
    stealthRecipient: new PublicKey(hexToBytes(stealthAddress.address)),
    amountCommitment: new Uint8Array(33),
    ephemeralPubkey: ephemeral33,
    viewingKeyHash: new Uint8Array(32),
    encryptedAmount: { nonce: new Uint8Array(24), ciphertext: new Uint8Array(0) },
    timestamp: 0n,
    claimed: false,
    tokenMint: null,
    bump: 255,
  }
}

describe("checkRecordOwnership (canonical view-only)", () => {
  it("detects a payment generated by generateStealthAddress (viewing private + spending public)", async () => {
    const { stealthAddress } = await generateStealthAddress(meta())
    const record = recordFor(stealthAddress)

    const detected = checkRecordOwnership(
      record,
      VIEWING_SEED, // viewing PRIVATE key
      ed25519.getPublicKey(SPENDING_SEED) // spending PUBLIC key — never the private key
    )

    expect(detected).toBe(true)
  })

  it("returns false for the wrong viewing key", async () => {
    const { stealthAddress } = await generateStealthAddress(meta())
    const record = recordFor(stealthAddress)

    expect(
      checkRecordOwnership(record, WRONG_VIEWING_SEED, ed25519.getPublicKey(SPENDING_SEED))
    ).toBe(false)
  })

  it("returns false for the wrong spending public key", async () => {
    const { stealthAddress } = await generateStealthAddress(meta())
    const record = recordFor(stealthAddress)

    expect(
      checkRecordOwnership(record, VIEWING_SEED, ed25519.getPublicKey(new Uint8Array(32).fill(0x44)))
    ).toBe(false)
  })

  it("returns false (does not throw) on a malformed ephemeral key", async () => {
    const { stealthAddress } = await generateStealthAddress(meta())
    const record = recordFor(stealthAddress)
    record.ephemeralPubkey = new Uint8Array(5) // too short to be a valid point after slice

    expect(
      checkRecordOwnership(record, VIEWING_SEED, ed25519.getPublicKey(SPENDING_SEED))
    ).toBe(false)
  })
})
